<div style="text-align:center;" > <img src="logo.png" alt="UMU logo" height="10px" width="100px"  style="display:block; margin-left:auto; margin-right:auto;">

# UMU Data Analysis and Visualization

Hitanghu Moses Mulongo - 2024-M132-20791

*Assignemt 1*

## About the Dataset

<p>This <b> Netflix Movies and TV Shows </b> dataset consists of listings of all the contents available on Netflix, described using below list of features:</p>

1. show_id: Unique ID for a content
2. type: Identifier - A Movie or TV Show
3. title: Title of the content
4. director: Director of the content
5. cast: Actors involved in the content
6. country: Country where the content was produced
7. date_added: Date it was added on Netflix
8.vrelease_year: Actual Release year of the content
9. rating: TV Rating of the content
10. duration: Total Duration - in minutes or number of seasons
11. listed_in: Genre
12. description: The summary description

<h2>Task: </h2>
<p>
Analyzing genres, release years, ratings. Define a Show class and filter family-friendly content <p>

<p> Helper class</p>

In [202]:
class df_analyzer:
    def __init__(self, df):
        self.df = df
    def show_columns(self):
        ''' 
        Shows all columns in the dataframe
        '''
        print(df.columns)
    def show_summary_stats(self):
        ''' displays summary stattistics '''
        return df.describe(include='all')
    def display_value_counts(self,col):
        '''
        Dispalys the quantity of values for each feature in the de
        '''
        print(df[col].value_counts())

<h2> Installing libraries </h2>

In [204]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\moshe\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\moshe\appdata\roaming\python\python312\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Moshe\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Moshe\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Moshe\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Moshe\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Moshe\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Moshe\AppData\Roaming\Python\Python312\site-packages)

<h2> Importing Libraries </h2>

In [206]:
import pandas as pd

Loading Dataset into pandas df and view first five rows

In [208]:
df = pd.read_csv("netflix_titles.csv")
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

<h4> Create the df analyzer object </h4>

In [210]:
analyzer = df_analyzer(df)

<h4> Display columns </h4>

In [212]:
analyzer.show_columns()

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [213]:
analyzer.show_summary_stats()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8807.000000,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,NaN,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,NaN,3207,1793,362,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

<h4> Show value counts for each some features </h4>

In [215]:
important_features = [] # list to store some features
important_features = list(df[['type','title','release_year','rating']])
for f in important_features: # looping through the features stored and display value counts
    analyzer.display_value_counts(f)

type
Movie      6131
TV Show    2676
Name: count, dtype: int64
title
Dick Johnson Is Dead                     1
Ip Man 2                                 1
Hannibal Buress: Comedy Camisado         1
Turbo FAST                               1
Masha's Tales                            1
                                        ..
Love for Sale 2                          1
ROAD TO ROMA                             1
Good Time                                1
Captain Underpants Epic Choice-o-Rama    1
Zubaan                                   1
Name: count, Length: 8807, dtype: int64
release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1959       1
1925       1
1961       1
1947       1
1966       1
Name: count, Length: 74, dtype: int64
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

<h4> TV Ratings to determine family friendliness; </h4>

<p>From the dataset the following shows are recommended for kids, older, all ages, family and all audiences </P>
<p>Family Friendly Ratings</p>
TV-Y, TV-Y7, TV-Y7-FV, TV-G, G, PG

<p> None Friendly ratings</p>
TV-14, TV-MA, R, PG-13, NC-17, UR

In [218]:
# variables to store content nature
family_friendly = 'Family Friendly'
none_family_friendly = 'Not Family Friendly'
#dictionary for content and their content nature
family_friendly_features = {'TV-Y':family_friendly,'TV-Y7':family_friendly,'TV-Y7-FV':family_friendly,
                            'TV-G':family_friendly,'G':family_friendly,'PG':family_friendly,
                            'TV-14':none_family_friendly, 'TV-MA':none_family_friendly,'R':none_family_friendly,
                            'PG-13':none_family_friendly,'NC-17':none_family_friendly,'UR':none_family_friendly
                            
                           }

<h4> Filter out the df to only include the required columns </h4>

In [238]:
important_df = df[important_features]
important_df.head(5)

      type                  title  release_year rating
0    Movie   Dick Johnson Is Dead          2020  PG-13
1  TV Show          Blood & Water          2021  TV-MA
2  TV Show              Ganglands          2021  TV-MA
3  TV Show  Jailbirds New Orleans          2021  TV-MA
4  TV Show           Kota Factory          2021  TV-MA

<h4>Creating a new column called comment and map it with values from the family friendly features dictionary</h4>

In [242]:
important_df.loc[:, 'comment'] = important_df['rating'].apply(
    lambda x: family_friendly_features[x] if x in family_friendly_features else "Unknown"
)
important_df

         type                  title  release_year rating              comment
0       Movie   Dick Johnson Is Dead          2020  PG-13  Not Family Friendly
1     TV Show          Blood & Water          2021  TV-MA  Not Family Friendly
2     TV Show              Ganglands          2021  TV-MA  Not Family Friendly
3     TV Show  Jailbirds New Orleans          2021  TV-MA  Not Family Friendly
4     TV Show           Kota Factory          2021  TV-MA  Not Family Friendly
...       ...                    ...           ...    ...                  ...
8802    Movie                 Zodiac          2007      R  Not Family Friendly
8803  TV Show            Zombie Dumb          2018  TV-Y7      Family Friendly
8804    Movie             Zombieland          2009      R  Not Family Friendly
8805    Movie                   Zoom          2006     PG      Family Friendly
8806    Movie                 Zubaan          2015  TV-14  Not Family Friendly

[8807 rows x 5 columns]

<h4> Filtering Actual Family Friendly content </h4>

In [247]:
family_friendy_df = important_df[important_df['comment'] == 'Family Friendly' ]
family_friendy_df

,type,title,release_year,rating,comment
6,Movie,My Little Pony: A New Generation,2021,PG,Family Friendly
23,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,2021,TV-Y,Family Friendly
34,TV Show,Tayo and Little Wizards,2020,TV-Y7,Family Friendly
37,TV Show,Angry Birds,2018,TV-Y7,Family Friendly
39,TV Show,Chhota Bheem,2021,TV-Y7,Family Friendly
...,...,...,...,...,...
8793,Movie,"Yours, Mine and Ours",2005,PG,Family Friendly
8795,TV Show,Yu-Gi-Oh! Arc-V,2015,TV-Y7,Family Friendly
8797,TV Show,Zak Storm,2016,TV-Y7,Family Friendly
8803,TV Show,Zombie Dumb,2018,TV-Y7,Family Friendly
8805,Movie,Zoom,2006,PG,Family Friendly

<p> <b> END of Assignment </b> </p>